### ISSUE TITLE
General image notes

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/beta_report#1]
1- Remove images from 
intro page> http://slco-2016.github.io/beta_report/pages/intro_intro.html
and last page > http://slco-2016.github.io/beta_report/pages/fut_sus.html

2 - On each page, place first image (or block quote) within text column at the top of the column. 

 3 - Style quotes within a red box. See image below for reference.
![screen shot 2016-06-17 at 11 28 16 am](https://cloud.githubusercontent.com/assets/15329140/16160748/9f1c1c74-347e-11e6-90c8-161cd2e3d260.png)

**Comment by kuanb** [comment]
1 done

**Comment by kuanb** [comment]
2 has been done w infogrpahics

**Comment by kuanb** [comment]
2 there were a few pages where it was strange but otherwise all have been moved up top

**Comment by kuanb** [comment]
3 was also another issue and is done
