### ISSUE TITLE
Homepage redesign

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/beta_report#2]
![betareporthomepage](https://cloud.githubusercontent.com/assets/15329140/16165734/84ec04ce-349a-11e6-9540-8dc127f67f6b.png)

**Comment by kuanb** [comment]
#eb6342
#a83e4e

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/16288940/aef4393a-38a5-11e6-9d87-fa546cb09f00.png)

**Comment by kuanb** [comment]
I think we should leave the alpha report...

**Comment by bpdesigns** [comment]
@kuanb  is that a question about removing the link to the alpha report?  I think we should keep it for sure

**Comment by kuanb** [comment]
yep thats what it was. cool we are on same page
