### ISSUE TITLE
infographics

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/beta_report#4]
![infogrx_percent](https://cloud.githubusercontent.com/assets/15329140/16165861/50eb8e64-349b-11e6-930d-02207fa8017b.png)
http://slco-2016.github.io/beta_report/pages/dev_currperf2.html

![infogrx_time](https://cloud.githubusercontent.com/assets/15329140/16165814/0f7d1b32-349b-11e6-8899-af7f7c0f567b.png)
http://slco-2016.github.io/beta_report/pages/dev_currperf3.html

![10monthcycle_infogrx](https://cloud.githubusercontent.com/assets/15329140/16165815/0f7fdcdc-349b-11e6-948f-763cf8a3419d.png)
http://slco-2016.github.io/beta_report/pages/dev_overv.html

**Comment by kuanb** [comment]
awesome!!

**Comment by kuanb** [comment]
ben golder loves these btw
