### ISSUE TITLE
content updates

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/beta_report#6]
Text revisions as comments in Google Doc https://docs.google.com/document/d/1o6ldKT5lc7opRhsyL6_TmEaOnRQn8V4ezmhECsqTfpA/edit

**Comment by kuanb** [comment]
This was made 24 hrs ago... Going off edits that are dated on the file as being in comments created around Jun 14

**Comment by kuanb** [comment]
Around 11 - 2 PM that day

**Comment by bpdesigns** [comment]
Sounds fine.
